# Let tmux start a non-login shell using the bash on PATH.
# This is the best cross-OS way to make start-up scripts work well.
set -g default-command "bash -i"

set -g mouse on

set -g default-terminal "screen-256color"

set -a terminal-features "xterm-256color:RGB"

set -g status-left-length 50
set -g status-right "#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null | sed 's/.*/[&] /') %I:%M %p %Y-%m-%d"
set -g status-right-length 60

# No delay for escape key
set -sg escape-time 0

# Unbind default prefix
unbind C-b

# Bind prefix to Ctrl+Space
set -g prefix C-Space

# Allow sending C-SP to the app running inside Tmux by pressing Ctrl and hitting Space twice.
bind C-Space send-prefix

# Press prefix + r to resize
bind r resize-window -A \; display-message "Window resized to active client"

# Use prefix + h/j/k/l to move between panes (Vim-style)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Recommended by NeoVim :checkhealth
set-option -g focus-events on

# Use Vi mode for movement
set -g mode-keys vi

# Start selection with v; copy with y; paste with `prefix + ]`
bind -T copy-mode-vi v send -X begin-selection

# On macOS, pipe into pbcopy.
if-shell "uname | grep -q Darwin" {
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
}

# On Linux with Wayland, pipe into wl-copy.
if-shell '[ -n "$WAYLAND_DISPLAY" ]' {
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
}

# On Linux with X11, pipe into xclip.
if-shell '[ -z "$WAYLAND_DISPLAY" ] && uname | grep -q Linux' {
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
}
