[tool.tartufo]
repo-path = "."
regex = true
entropy = true

exclude-path-patterns = [
    {path-pattern = 'tartufo\.toml$', reason = 'contains many high entropy signatures'},
]

exclude-entropy-patterns = [
    {path-pattern = "dotfiles/\\.bashrc$", pattern = "\\$KXUE43_SUBSTANCE_DIR/lib/\\S+\\.sh", reason = "source path references are not credentials"},
    {path-pattern = "profile/ascd\\.bashrc$", pattern = "\\$KXUE43_SUBSTANCE_DIR/lib/\\S+\\.sh", reason = "source path references are not credentials"},
    {path-pattern = "profile/kxue43\\.bashrc$", pattern = "\\$KXUE43_SUBSTANCE_DIR/lib/\\S+\\.sh", reason = "source path references are not credentials"},
]

exclude-signatures = [
    {signature = "f778aaca32f07db00e1a7ca8270caccb1007f7916aea3274313a9de29fd76e5e", reason = "false positive of GPG public key signature in .gitconfig file"},
    {signature = "2e24f3c6a6e0c19dd4000edca4cf9459f3b2537af98cb4be2fdb5814765cc137", reason = "GPG signing key ID is not credential"},
]
